version: '3'

services:
  server:
    container_name: truenorth-server
    restart: always
    build: .
    ports:
      - '3001:8082'
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: truenorth-mongo
    image: mongo:4.4.6
    ports:
      - '27017:27017'